# netlify.toml

[build]
  command = "npm run build"
  publish = "build"

# Stripe Checkout → Firebase Function (or switch to Netlify function if you used that)
[[redirects]]
  from = "/createCheckoutSession"
  to = "https://us-central1-review-45013.cloudfunctions.net/createCheckoutSession"
  status = 200

# Stripe Customer Portal → Firebase Function
[[redirects]]
  from = "/createPortalSession"
  to = "https://us-central1-review-45013.cloudfunctions.net/createPortalSession"
  status = 200

# .edu OTP endpoints (keep)
[[redirects]]
  from = "/sendEduOtp"
  to = "https://us-central1-review-45013.cloudfunctions.net/sendEduOtp"
  status = 200

[[redirects]]
  from = "/verifyEduOtp"
  to = "https://us-central1-review-45013.cloudfunctions.net/verifyEduOtp"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
